### ISSUE TITLE
Link broken in readme

### ISSUE THREAD

**Issue by davide-targa** [rjshade/gmaps-autocomplete#2]
Hi rjshade,
I noticed that the second link in the readme file (README.md) is broken.
If I'm not wrong the correct link should be:
http://rjshade.com/2012/03/27/Google-Maps-autocomplete-with-jQuery-UI/

Hope this helps :-)

Regards,
Davide

**Comment by rjshade** [comment]
Fixed, thanks!

On 15 September 2012 18:38, Davide notifications@github.com wrote:

> Hi rjshade,
> I noticed that the second link in the readme file (README.md) is broken.
> If I'm not wrong the correct link should be:
> http://rjshade.com/2012/03/27/Google-Maps-autocomplete-with-jQuery-UI/
> 
> Hope this helps :-)
> 
> Regards,
> Davide
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rjshade/gmaps-autocomplete/issues/2.

## 

Robbie Shade

e: robbie.shade@gmail.com
t: 07939 970283

:wq
